extend type Mutation {
  """
  ✨ Insert a single `Activity` into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  activity_insert(
    """
    Data object to insert into the table.
    """
    data: Activity_Data!
  ): Activity_KeyOutput! @fdc_generated(from: "Activity", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Place` into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  place_insert(
    """
    Data object to insert into the table.
    """
    data: Place_Data!
  ): Place_KeyOutput! @fdc_generated(from: "Place", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Activity` objects into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  activity_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Activity_Data!]!
  ): [Activity_KeyOutput!]! @fdc_generated(from: "Activity", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Place` objects into the table. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  place_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Place_Data!]!
  ): [Place_KeyOutput!]! @fdc_generated(from: "Place", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Activity` into the table, based on the primary key. Returns the key of the newly inserted `Activity`.
  """
  activity_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Activity_Data!
  ): Activity_KeyOutput! @fdc_generated(from: "Activity", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Place` into the table, based on the primary key. Returns the key of the newly inserted `Place`.
  """
  place_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Place_Data!
  ): Place_KeyOutput! @fdc_generated(from: "Place", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Activity` objects into the table, based on the primary key. Returns the key of the newly inserted `Activity`.
  """
  activity_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Activity_Data!]!
  ): [Activity_KeyOutput!]! @fdc_generated(from: "Activity", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Place` objects into the table, based on the primary key. Returns the key of the newly inserted `Place`.
  """
  place_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Place_Data!]!
  ): [Place_KeyOutput!]! @fdc_generated(from: "Place", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Activity` based on `id`, `key` or `first`, setting columns specified in `data`. Returns `null` if not found.
  """
  activity_update(
    """
    The key used to identify the object.
    """
    key: Activity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Activity_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Activity_Data!
  ): Activity_KeyOutput @fdc_generated(from: "Activity", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Place` based on `id`, `key` or `first`, setting columns specified in `data`. Returns `null` if not found.
  """
  place_update(
    """
    The key used to identify the object.
    """
    key: Place_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Place_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Place_Data!
  ): Place_KeyOutput @fdc_generated(from: "Place", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Activity` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  activity_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Activity_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Activity_Data!
  ): Int! @fdc_generated(from: "Activity", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Place` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  place_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Place_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Place_Data!
  ): Int! @fdc_generated(from: "Place", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Activity` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  activity_delete(
    """
    The key used to identify the object.
    """
    key: Activity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Activity_FirstRow
  ): Activity_KeyOutput @fdc_generated(from: "Activity", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Place` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  place_delete(
    """
    The key used to identify the object.
    """
    key: Place_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Place_FirstRow
  ): Place_KeyOutput @fdc_generated(from: "Place", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Activity` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  activity_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Activity_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Activity", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Place` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  place_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Place_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Place", purpose: DELETE_MULTIPLE)
}
